name: sadgun-testing-workflow-hands-on

on:
    workflow_dispatch
#   push:
#     branches:
#       - main

jobs:
  test1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: echo "Hello World"