name: test-workflow

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: install node js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
        
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: Install dependencies
        run: npm ci
          
      - name: Build projetc
        run: npm run bild

      - name: Deploy
        run: echo "deploy"